name: SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'

    - name: Install global tools
      run: |
        dotnet tool install --global dotnet-sonarscanner
        dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Begin SonarCloud analysis
      run: |
        dotnet sonarscanner begin /k:"Hritam9_sonarqube-dotnet-poc" /o:"hritam9" `
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}" `
          /d:sonar.cs.vscoveragexml.reportsPaths="**/coverage.cobertura.xml"

    - name: Restore dependencies
      run: dotnet restore myapp.sln

    - name: Build project
      run: dotnet build myapp.sln --no-restore

    - name: Run tests with code coverage
      run: dotnet test myapp.sln --collect:"XPlat Code Coverage" --results-directory TestResults

    - name: Convert coverage to Cobertura
      run: |
        reportgenerator -reports:"TestResults/**/coverage.cobertura.xml" -targetdir:"coverage-report" -reporttypes:"Cobertura"

    - name: End SonarCloud analysis
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
