name: SonarCloud .NET Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build, Test, and Analyze
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Add .NET tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin SonarCloud analysis
        run: >
          dotnet sonarscanner begin
          /k:"Hritam9_sonarqube-dotnet-poc"
          /o:"hritam9"
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          /d:sonar.cs.vscoveragexml.reportsPaths="**/*.coverage.cobertura.xml"

      - name: Restore dependencies
        run: dotnet restore myapp.sln

      - name: Build solution
        run: dotnet build myapp.sln --no-restore

      - name: Run tests with coverage
        run: dotnet test MyApp.Tests/MyApp.Tests.csproj --no-build --collect:"XPlat Code Coverage"

      - name: Convert coverage to Cobertura format
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coveragereport

      - name: End SonarCloud analysis
        run: >
          dotnet sonarscanner end
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
