name: Build and analyze .NET app with SonarCloud

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'

    - name: Install dotnet coverage tool
      run: dotnet tool install --global dotnet-coverage

    - name: Restore dependencies
      run: dotnet restore MyApp.sln

    - name: Begin SonarCloud analysis
      run: |
        dotnet sonarscanner begin /k:"Hritam9_sonarqube-dotnet-poc" /o:"hritam9" `
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}" `
          /d:sonar.cs.vscoveragexml.reportsPaths="**/*.coverage.cobertura.xml"
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Build solution
      run: dotnet build MyApp.sln --no-incremental

    - name: Run tests with coverage
      run: |
        dotnet-coverage collect "dotnet test MyApp.Tests/MyApp.Tests.csproj --no-build" `
          -f cobertura -o "coverage.cobertura.xml"

    - name: End SonarCloud analysis
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
