name: SonarQube .NET Coverage PoC

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Begin SonarQube Analysis
      run: |
       dotnet sonarscanner begin \
       /k:"myapp-key" \
       /d:sonar.host.url="http://172.20.10.3:9004" \
       /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
       /d:sonar.cs.vscoveragexml.reportsPaths="**/*.coverage.cobertura.xml"

    - name: Build the App
      run: dotnet build --no-incremental

    - name: Run Tests and Collect Coverage
      run: dotnet test MyApp.Tests --collect:"XPlat Code Coverage" --results-directory TestResults

    - name: End SonarQube Analysis
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
